### ISSUE TITLE
Upgrades

### ISSUE THREAD

**Issue by jackel1138** [jackinloadup/lunatic-fringe#2]
Health
Fuel
Spare parts
Weapons
Boost
Invulnerability
Double Points

**Comment by jackinloadup** [comment]
@schwal10  what if any of these upgrades are still in progress. Can you summaries where you think upgrades are in relation to the original game play or what your thoughts are here ^_^

**Comment by schwal10** [comment]
@jackinloadup So all upgrades (or powerups, as I refer to them) are now in the game and have appropriate functionality. I would argue that after the entire game functionality is complete a sweep should probably be done to tweak the game to get it as close as possible to the original, but in terms of this issue I would say it can be closed since all of the upgrades are in the game. Might be worth opening an issue for making things closer to the original at some point though since I am going off of my very limited memory for a lot of the functionality I added.

**Comment by jackinloadup** [comment]
Totally get it. I agree I'll create another ticket for attempting to bring the details in line with the original.

I marked v1.0 as being able to operate true to the original. Which I still think makes sense. As I'm sure you have played with. It might be fun to create a "trainer" or similar built in modifying tool to expose number of enemies, number of lives, ect ect. Maybe it's a game mode system and one of the game modes is "original".  or it could just be a panel where you live change the number of things. Either way that was a fun way to pass the time.

Again thanks for the contribution!
